services:
  - type: web
    name: eventapp
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./prisma/production.db
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        fromDatabase: true
      - key: CLERK_SECRET_KEY
        fromDatabase: true
      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: /sign-in
      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: /sign-up
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: /dashboard
      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: /dashboard
      - key: RESEND_API_KEY
        fromDatabase: true
      - key: RESEND_FROM_EMAIL
        fromDatabase: true 